### ISSUE TITLE
IndentationError-Predictor.py_Line141

### ISSUE THREAD

**Issue by Kris-Tate** [shendurelab/Lindel#1]
Hi Will, 

I am attempting to use Lindel at the command line. I have followed instructions from the link (https://shendurelab.github.io/Lindel/docs/#installing-local-lindel-from-github), however I consistently receive an error when running the test_seq provided. 

Pasted from my terminal:

```
(Lindel) bash-3.2$ python Lindel_prediction.py TAACGTTATCAACGCCTATATTAAAGCGACCGTCGGTTGAACTGCGTGGATCAATGCGTC test_seq
Traceback (most recent call last):
  File "Lindel_prediction.py", line 12, in <module>
    from Lindel.Predictor import * 
  File "/Users/kris_tate/Lindel/Lindel/Predictor.py", line 141
    combine = []
               ^
IndentationError: unindent does not match any outer indentation level
```
Any assistance would be greatly appreciated, 

Thank you very much, 

Kris

**Comment by willchen108** [comment]
Hi Kris, thank you for your feedback. I think the problem should be fixed now. try it again and let me know if you meet the same issue or any other errors. Best
